export const ALL_FOODITEM_REQUEST = "ALL_FOODITEM_REQUEST";
export const ALL_FOODITEM_SUCCESS = "ALL_FOODITEM_SUCCESS";
export const ALL_FOODITEM_FAIL = "ALL_FOODITEM_FAIL";
export const CLEAR_ERRORS = "CLEAR_ERRORS";